# .github/workflows/main.yml mein paste karein
name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Jab bhi 'main' branch par naya code aaye, deploy karo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Yeh '/root' folder ko indicate karta hai (jahan index.html hai)
          force_orphan: true
